import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { EXAMPLES, buildAllExamples, buildModulePair } from '../scripts/examples.js';
import { decodeStream } from '../src/lang/format.js';
import { verifyModule } from '../src/lang/semantic.js';
import { runProject } from '../src/lang/project.js';

describe('documentation examples (generated by the real encoder)', () => {
  it('contains 10 beginner, 10 intermediate and 5 advanced examples', () => {
    expect(EXAMPLES.filter((e) => e.level === 'beginner')).toHaveLength(10);
    expect(EXAMPLES.filter((e) => e.level === 'intermediate')).toHaveLength(10);
    expect(EXAMPLES.filter((e) => e.level === 'advanced')).toHaveLength(5);
  });

  it('every example encodes to pure 6/7 source', async () => {
    const built = await buildAllExamples();
    for (const b of built) {
      expect(/^[67]+$/.test(b.stream)).toBe(true);
      expect(b.ok).toBe(true);
    }
  });

  it('every example decodes, parses and verifies through the real pipeline', async () => {
    const built = await buildAllExamples();
    for (const b of built) {
      const mod = decodeStream(b.stream);
      expect(() => verifyModule(mod)).not.toThrow();
    }
  });

  it('hello world decodes, parses, executes and prints Hello, World!', async () => {
    const built = await buildAllExamples();
    const hw = built.find((b) => b.def.id === 'hello-world')!;
    const r = await runProject({ 'main.67': hw.stream });
    expect(r.ok).toBe(true);
    expect(r.output).toBe('Hello, World!\n');
  });

  it('a binary function example decodes and executes', async () => {
    const built = await buildAllExamples();
    const fn = built.find((b) => b.def.id === 'function')!;
    const r = await runProject({ 'main.67': fn.stream });
    expect(r.ok).toBe(true);
    expect(r.output).toBe('42\n');
  });
});

describe('shipped .67 files in public/examples', () => {
  const dir = join(process.cwd(), 'public', 'examples');

  it('exists and contains .67 source files', () => {
    const files = readdirSync(dir).filter((f) => f.endsWith('.67'));
    expect(files.length).toBeGreaterThanOrEqual(25);
  });

  it('every shipped .67 file contains only 6 and 7', () => {
    const files = readdirSync(dir).filter((f) => f.endsWith('.67'));
    for (const f of files) {
      const content = readFileSync(join(dir, f), 'utf8');
      expect(/^[67]+$/.test(content), `${f} must contain only 6/7`).toBe(true);
      expect(() => verifyModule(decodeStream(content)), `${f} must verify`).not.toThrow();
    }
  });

  it('the two-file module example imports across files', async () => {
    const pair = buildModulePair();
    const r = await runProject({ 'main.67': pair.main, 'mathlib.67': pair.math });
    expect(r.ok).toBe(true);
    expect(r.output).toBe(pair.expected);
  });
});
