/**
 * 67 workstation UI. The editor only ever displays/edits raw 6/7 source.
 * Readable information (disassembly, docs, diagnostics) lives in separate
 * panels and never replaces the binary editor.
 */

import { ProjectFile, ProjectStorage, loadSettings, saveSettings, Settings } from '../app/storage.js';
import { validateSource } from '../app/validate.js';
import { decodeStream, disassemble, moduleToStream, OP_SPEC, Module } from '../lang/format.js';
import { runProject } from '../lang/project.js';
import { ModuleBuilder } from '../lang/assembler.js';
import { softWrap } from '../lang/bits.js';
import { LIMITS } from '../lang/limits.js';
import { DOCS_HTML } from './docs.js';
import examplesManifest from '../../examples-data/index.json';
import './sw-register.js';

const $ = <T extends HTMLElement>(id: string): T => document.getElementById(id) as T;

const editor = $<HTMLTextAreaElement>('editor');
const gutter = $<HTMLPreElement>('gutter');
const statusLine = $<HTMLDivElement>('status-line');
const terminal = $<HTMLPreElement>('terminal');
const fileList = $<HTMLUListElement>('file-list');
const fileCount = $<HTMLSpanElement>('file-count');
const editorTitle = $<HTMLSpanElement>('editor-title');
const editorMeta = $<HTMLSpanElement>('editor-meta');
const termInputRow = $<HTMLDivElement>('term-input-row');
const termInput = $<HTMLInputElement>('term-input');

let settings: Settings = loadSettings();
const storage = new ProjectStorage();

interface State {
  files: Record<string, ProjectFile>;
  current: string;
  running: boolean;
  abort: AbortController | null;
  inputQueue: string[];
  inputWaiter: ((v: string) => void) | null;
  stdout: string;
  stderr: string;
  showStderr: boolean;
}

const state: State = {
  files: {},
  current: 'main.67',
  running: false,
  abort: null,
  inputQueue: [],
  inputWaiter: null,
  stdout: '',
  stderr: '',
  showStderr: false,
};

function renderTerminal(): void {
  terminal.textContent = state.showStderr ? state.stderr : state.stdout;
  terminal.classList.toggle('stderr-view', state.showStderr);
  terminal.scrollTop = terminal.scrollHeight;
}

// ---------------------------------------------------------------------------
// Default program: Hello World generated by the real encoder.
function defaultProgram(): string {
  const b = new ModuleBuilder('main');
  b.root.loadStr('Hello, World!');
  b.root.callBuiltin('print', 1);
  b.root.null();
  b.root.return();
  return moduleToStream(b.build());
}

// ---------------------------------------------------------------------------
async function boot(): Promise<void> {
  await storage.init();
  const loaded = await storage.loadAll();
  if (Object.keys(loaded).length > 0) {
    state.files = loaded;
  } else {
    state.files = {
      'main.67': { name: 'main.67', content: defaultProgram(), updated: Date.now() },
    };
    await storage.save(state.files['main.67']);
  }
  state.current = state.files['main.67'] ? 'main.67' : Object.keys(state.files)[0];
  renderFileList();
  loadFileIntoEditor(state.current);
  bindUI();
  setStatus('Ready · 67 runtime', 'ok');
}

function renderFileList(): void {
  fileList.innerHTML = '';
  const names = Object.keys(state.files).sort();
  for (const name of names) {
    const li = document.createElement('li');
    if (name === state.current) li.classList.add('active');
    const label = document.createElement('span');
    label.textContent = name;
    li.appendChild(label);
    const del = document.createElement('span');
    del.className = 'del';
    del.textContent = '×';
    del.title = 'delete file';
    del.onclick = (e) => {
      e.stopPropagation();
      if (names.length <= 1) return;
      delete state.files[name];
      void storage.remove(name);
      if (state.current === name) {
        state.current = Object.keys(state.files).sort()[0];
        loadFileIntoEditor(state.current);
      }
      renderFileList();
    };
    li.appendChild(del);
    li.onclick = () => {
      saveCurrent();
      state.current = name;
      loadFileIntoEditor(name);
      renderFileList();
    };
    fileList.appendChild(li);
  }
  fileCount.textContent = `${names.length} file${names.length === 1 ? '' : 's'}`;
}

function loadFileIntoEditor(name: string): void {
  const f = state.files[name];
  if (!f) return;
  state.current = name;
  editor.value = f.content;
  editorTitle.textContent = name;
  renderGutter();
  runValidation();
}

function currentFile(): ProjectFile {
  if (!state.files[state.current]) {
    state.files[state.current] = { name: state.current, content: '', updated: Date.now() };
  }
  return state.files[state.current];
}

function saveCurrent(): void {
  const f = currentFile();
  f.content = editor.value;
  f.updated = Date.now();
  void storage.save(f);
}

function renderGutter(): void {
  const lines = softWrap(editor.value, settings.wrapWidth);
  const nums: string[] = [];
  for (let i = 0; i < lines.length; i++) {
    nums.push(String(i * settings.wrapWidth));
  }
  gutter.textContent = nums.join('\n');
  gutter.style.fontSize = `${settings.fontSize}px`;
  editor.style.fontSize = `${settings.fontSize}px`;
}

function setStatus(msg: string, cls = ''): void {
  statusLine.innerHTML = '';
  const span = document.createElement('span');
  span.className = cls;
  span.textContent = msg;
  statusLine.appendChild(span);
  const cursor = cursorInfo();
  if (cursor) {
    const c = document.createElement('span');
    c.textContent = cursor;
    statusLine.appendChild(c);
  }
}

function cursorInfo(): string {
  const pos = editor.selectionStart ?? 0;
  const line = Math.floor(pos / settings.wrapWidth) + 1;
  const col = (pos % settings.wrapWidth) + 1;
  return `bit ${pos} · byte ${Math.floor(pos / 8)} · Ln ${line}, Col ${col}`;
}

let validationTimer: ReturnType<typeof setTimeout> | null = null;
function runValidation(): void {
  const src = editor.value;
  editorMeta.textContent = `${src.length} symbols · ${Math.floor(src.length / 8)} bytes`;
  const result = validateSource(src, settings.wrapWidth);
  if (result.ok) {
    setStatus(`Valid module${result.diagnostics.length ? ' (warnings)' : ''} · 67 runtime`, 'ok');
  } else {
    const d = result.diagnostics[0];
    setStatus(`${d.message} — bit ${d.bitOffset}, Ln ${d.line}, Col ${d.col}`, 'err');
  }
  renderGutter();
}

editor.addEventListener('input', () => {
  if (validationTimer) clearTimeout(validationTimer);
  validationTimer = setTimeout(() => {
    saveCurrent();
    runValidation();
  }, 250);
  renderGutter();
});
editor.addEventListener('scroll', () => {
  gutter.scrollTop = editor.scrollTop;
});
editor.addEventListener('keyup', () => setStatusFromValidation());
editor.addEventListener('click', () => setStatusFromValidation());

function setStatusFromValidation(): void {
  runValidation();
}

// ---------------------------------------------------------------------------
// Running
const btnRun = $<HTMLButtonElement>('btn-run');
const btnStop = $<HTMLButtonElement>('btn-stop');

function appendOutput(text: string, stream: 'out' | 'err' = 'out'): void {
  if (stream === 'err') {
    state.stderr += text;
    setStderrBadge();
  } else {
    state.stdout += text;
  }
  renderTerminal();
}

function setStderrBadge(): void {
  const tab = $<HTMLSpanElement>('tab-stderr');
  tab.innerHTML = state.stderr ? 'stderr <span class="badge">●</span>' : 'stderr';
}

async function runProgram(): Promise<void> {
  saveCurrent();
  const src = editor.value;
  const validation = validateSource(src, settings.wrapWidth);
  if (!validation.ok) {
    appendOutput(`Compile error: ${validation.diagnostics[0].message}\n`, 'err');
    return;
  }
  // Build a project snapshot: every file currently stored.
  const files: Record<string, string> = {};
  for (const [name, f] of Object.entries(state.files)) files[name] = f.content;

  state.stdout = '';
  state.stderr = '';
  state.showStderr = false;
  renderTerminal();
  setStderrBadge();
  state.abort = new AbortController();
  state.running = true;
  btnRun.disabled = true;
  btnStop.disabled = false;
  setStatus('Running…');
  const started = performance.now();

  const result = await runProject(files, {
    entry: state.current,
    signal: state.abort.signal,
    io: {
      print: (t) => {
        appendOutput(t, 'out');
      },
      input: (prompt) => handleInput(prompt),
    },
    maxInstructions: LIMITS.maxInstructions,
    timeoutMs: LIMITS.defaultTimeoutMs,
  });

  const ms = Math.round(performance.now() - started);
  if (!result.ok && result.error) {
    appendOutput(result.error + '\n', 'err');
    setStatus(`Runtime error · ${ms} ms`, 'err');
  } else {
    setStatus(`Finished · ${ms} ms`, 'ok');
  }
  state.running = false;
  state.abort = null;
  btnRun.disabled = false;
  btnStop.disabled = true;
  termInputRow.hidden = true;
}

function handleInput(prompt: string): Promise<string> {
  appendOutput(prompt);
  termInputRow.hidden = false;
  termInput.value = '';
  termInput.focus();
  return new Promise((resolve) => {
    state.inputWaiter = (v) => {
      appendOutput(v + '\n');
      resolve(v);
    };
  });
}

termInput.addEventListener('keydown', (e) => {
  if (e.key === 'Enter') {
    const v = termInput.value;
    termInputRow.hidden = true;
    state.inputWaiter?.(v);
    state.inputWaiter = null;
  }
});

// ---------------------------------------------------------------------------
// Inspector
function showInspector(): void {
  const pane = $<HTMLElement>('right-pane');
  const body = $<HTMLDivElement>('right-body');
  $<HTMLSpanElement>('right-title').textContent = 'Instruction inspector';
  pane.hidden = false;
  const src = editor.value;
  try {
    const mod: Module = decodeStream(src);
    let html = `<h3>Module</h3><table>
      <tr><th>constants</th><td>${mod.constants.length}</td></tr>
      <tr><th>functions</th><td>${mod.functions.length}</td></tr>
      <tr><th>imports</th><td>${mod.imports.length}</td></tr>
      <tr><th>exports</th><td>${mod.exports.length}</td></tr></table>`;
    mod.functions.forEach((fn, i) => {
      const name = fn.nameConst !== 0xffffffff && mod.constants[fn.nameConst]?.kind === 'str'
        ? (mod.constants[fn.nameConst] as { value: string }).value
        : (i === 0 ? '<module initializer>' : `<fn#${i}>`);
      html += `<h3>function ${i}: ${escapeHtml(name)}</h3><table>
        <tr><th>params</th><td>${fn.params.length}</td><th>locals</th><td>${fn.localCount}</td></tr>
        <tr><th>code bytes</th><td>${fn.code.length}</td><th>try regions</th><td>${fn.tries.length}</td></tr></table>`;
      html += '<table><tr><th>bit</th><th>byte</th><th>opcode</th><th>operands</th><th>hex</th></tr>';
      try {
        for (const ins of disassemble(fn)) {
          html += `<tr><td class="bits">${ins.bitOffset}</td><td class="bits">${ins.offset}</td><td class="op-name">${ins.name}</td><td>${ins.operands.join(', ')}</td><td class="bits">${ins.raw}</td></tr>`;
        }
      } catch (e) {
        html += `<tr><td colspan="5" class="bits">${escapeHtml(e instanceof Error ? e.message : String(e))}</td></tr>`;
      }
      html += '</table>';
    });
    html += '<h3>Constant pool</h3><table><tr><th>#</th><th>tag</th><th>value</th></tr>';
    mod.constants.forEach((c, i) => {
      html += `<tr><td class="bits">${i}</td><td>${c.kind}</td><td>${escapeHtml(c.kind === 'str' ? c.value : String(c.kind === 'int' ? c.value : c.value))}</td></tr>`;
    });
    html += '</table>';
    body.innerHTML = html;
  } catch (e) {
    body.textContent = `Cannot inspect: ${e instanceof Error ? e.message : String(e)}`;
  }
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' })[c] as string);
}

// ---------------------------------------------------------------------------
// Modals
const overlay = $<HTMLDivElement>('modal-overlay');
function openModal(title: string, bodyHtml: string): void {
  $<HTMLSpanElement>('modal-title').textContent = title;
  $<HTMLDivElement>('modal-body').innerHTML = bodyHtml;
  overlay.hidden = false;
}
function closeModal(): void {
  overlay.hidden = true;
}

function showExamples(): void {
  const items = (examplesManifest as Array<{ id: string; title: string; level: string; description: string; output: string }>)
    .map(
      (e) =>
        `<button class="example-item" data-id="${e.id}">
          <span class="lvl">${e.level}</span>
          <span class="t">${escapeHtml(e.title)}</span>
          <div class="d">${escapeHtml(e.description)} — outputs ${escapeHtml(JSON.stringify(e.output.trim()))}</div>
        </button>`,
    )
    .join('');
  openModal('Examples (binary source, encoded by the real compiler)', items + noteAboutModules());
  document.querySelectorAll<HTMLButtonElement>('.example-item').forEach((btn) => {
    btn.onclick = () => {
      const id = btn.dataset.id!;
      void loadExample(id);
      closeModal();
    };
  });
}

function noteAboutModules(): string {
  return `<div class="d" style="margin-top:10px;color:var(--text-faint)">
    The module example ships as two files: module-main.67 and module-mathlib.67.
    Use Import to load both, then open module-main.67 and press Run.
  </div>`;
}

async function loadExample(id: string): Promise<void> {
  const res = await fetch(`./examples/${id}.67`);
  const content = await res.text();
  const name = id === 'hello-world' ? 'main.67' : `${id}.67`;
  state.files[name] = { name, content: content.trim(), updated: Date.now() };
  await storage.save(state.files[name]);
  renderFileList();
  loadFileIntoEditor(name);
}

function showDocs(): void {
  const pane = $<HTMLElement>('right-pane');
  $<HTMLSpanElement>('right-title').textContent = 'Docs';
  pane.hidden = false;
  $<HTMLDivElement>('right-body').innerHTML = `<div class="doc">${DOCS_HTML}</div>`;
}

function showSettings(): void {
  openModal(
    'Settings',
    `<label style="display:block;margin:8px 0">Visual wrap width (symbols per line)
      <input id="set-wrap" type="number" min="16" max="256" value="${settings.wrapWidth}" style="width:80px;margin-left:8px;background:var(--bg-input);color:var(--text);border:1px solid var(--border);padding:3px 6px"/>
    </label>
    <label style="display:block;margin:8px 0">Editor font size (px)
      <input id="set-font" type="number" min="10" max="24" value="${settings.fontSize}" style="width:80px;margin-left:8px;background:var(--bg-input);color:var(--text);border:1px solid var(--border);padding:3px 6px"/>
    </label>
    <div class="d" style="color:var(--text-faint);margin-top:12px">
      Runtime limits: ${LIMITS.maxInstructions.toLocaleString()} instructions,
      ${LIMITS.maxCallDepth} call depth,
      ${(LIMITS.maxOutputBytes / 1024).toFixed(0)} KiB output cap.
    </div>`,
  );
  $<HTMLInputElement>('set-wrap').oninput = (e) => {
    settings.wrapWidth = Number((e.target as HTMLInputElement).value) || 64;
    saveSettings(settings);
    renderGutter();
    runValidation();
  };
  $<HTMLInputElement>('set-font').oninput = (e) => {
    settings.fontSize = Number((e.target as HTMLInputElement).value) || 14;
    saveSettings(settings);
    renderGutter();
  };
}

// ---------------------------------------------------------------------------
// File import / export / download
const fileInput = $<HTMLInputElement>('file-input');

function newFile(): void {
  const name = prompt('New file name (must end in .67):', 'untitled.67');
  if (!name) return;
  const fname = name.endsWith('.67') ? name : name + '.67';
  state.files[fname] = { name: fname, content: '', updated: Date.now() };
  void storage.save(state.files[fname]);
  renderFileList();
  loadFileIntoEditor(fname);
}

function downloadFile(): void {
  saveCurrent();
  const blob = new Blob([editor.value], { type: 'text/plain' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = state.current;
  a.click();
  URL.revokeObjectURL(a.href);
}

function exportProject(): void {
  saveCurrent();
  const files = Object.values(state.files);
  const blob = new Blob([JSON.stringify({ version: 1, files }, null, 2)], { type: 'application/json' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = '67-project.json';
  a.click();
  URL.revokeObjectURL(a.href);
}

fileInput.addEventListener('change', async () => {
  const files = Array.from(fileInput.files ?? []);
  for (const file of files) {
    const text = await file.text();
    if (file.name.endsWith('.json')) {
      try {
        const imported = await storage.importProject(text);
        for (const f of imported) {
          state.files[f.name] = f;
          await storage.save(f);
        }
      } catch (e) {
        appendOutput(`Import failed: ${e instanceof Error ? e.message : String(e)}\n`, 'err');
      }
    } else {
      const name = file.name.endsWith('.67') ? file.name : file.name + '.67';
      const content = text.trim();
      state.files[name] = { name, content, updated: Date.now() };
      await storage.save(state.files[name]);
    }
  }
  renderFileList();
  loadFileIntoEditor(state.current);
  fileInput.value = '';
});

// ---------------------------------------------------------------------------
// Search / replace + keyboard shortcuts
function openSearch(): void {
  const needle = prompt('Find (6/7 sequence):');
  if (needle === null) return;
  const idx = editor.value.indexOf(needle, (editor.selectionEnd ?? 0));
  if (idx === -1) {
    setStatus(`No match for ${JSON.stringify(needle)}`, 'err');
    return;
  }
  editor.focus();
  editor.setSelectionRange(idx, idx + needle.length);
  const replace = prompt('Replace with? (leave empty to just find)', '');
  if (replace !== null && replace !== '') {
    editor.setRangeText(replace, idx, idx + needle.length, 'select');
    saveCurrent();
    runValidation();
  }
}

function bindUI(): void {
  btnRun.onclick = () => void runProgram();
  btnStop.onclick = () => state.abort?.abort();
  $<HTMLButtonElement>('btn-save').onclick = () => {
    saveCurrent();
    setStatus('Saved', 'ok');
  };
  $<HTMLButtonElement>('btn-new').onclick = newFile;
  $<HTMLButtonElement>('btn-add-file').onclick = newFile;
  $<HTMLButtonElement>('btn-import').onclick = () => fileInput.click();
  $<HTMLButtonElement>('btn-export').onclick = exportProject;
  $<HTMLButtonElement>('btn-download').onclick = downloadFile;
  $<HTMLButtonElement>('btn-examples').onclick = showExamples;
  $<HTMLButtonElement>('btn-inspect').onclick = showInspector;
  $<HTMLButtonElement>('btn-docs').onclick = showDocs;
  $<HTMLButtonElement>('btn-settings').onclick = showSettings;
  $<HTMLButtonElement>('btn-close-right').onclick = () => ($<HTMLElement>('right-pane').hidden = true);
  $<HTMLButtonElement>('modal-close').onclick = closeModal;
  overlay.onclick = (e) => {
    if (e.target === overlay) closeModal();
  };
  $<HTMLButtonElement>('btn-clear-term').onclick = () => {
    state.stdout = '';
    state.stderr = '';
    renderTerminal();
    setStderrBadge();
  };
  $<HTMLSpanElement>('tab-stdout').onclick = () => {
    state.showStderr = false;
    renderTerminal();
    $<HTMLSpanElement>('tab-stdout').classList.add('active');
    $<HTMLSpanElement>('tab-stderr').classList.remove('active');
  };
  $<HTMLSpanElement>('tab-stderr').onclick = () => {
    state.showStderr = true;
    renderTerminal();
    $<HTMLSpanElement>('tab-stderr').classList.add('active');
    $<HTMLSpanElement>('tab-stdout').classList.remove('active');
  };

  editor.addEventListener('keydown', (e) => {
    if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') {
      e.preventDefault();
      void runProgram();
    } else if ((e.ctrlKey || e.metaKey) && e.key === 's') {
      e.preventDefault();
      saveCurrent();
      setStatus('Saved', 'ok');
    } else if ((e.ctrlKey || e.metaKey) && e.key === 'f') {
      e.preventDefault();
      openSearch();
    } else if (e.key === 'Tab') {
      // Tab moves focus by default; inserting bits is left to the palette.
    }
  });
}

void boot();

// Referenced so OP_SPEC is available in the bundle for future inspector use.
void OP_SPEC;
